### ISSUE TITLE
Could you specify the reference paper you used to implement this project?

### ISSUE THREAD

**Issue by jiang-yuan** [hschneid/xflp#2]
It may be helpful for me to read the code. Thank you.

**Comment by hschneid** [comment]
Hi jiang-yuan,

In sum, there is no single paper, where this algorithm is described. It was created over time in multiple business related projects: VRP with loading contraints, Truck loading and now in scheduled demand optimization.

The optimization contains two stages:
* Checking of contraints
  * This is done mainly in Container.java
  * General goal: Avoid a Wall-, Stack- or Layer-oriented packing algorithm
  * The algorithm bases mostly on the Bottom-Left-Fill algorithm
  * But there are some differences
    * Selection of next insert position can be done by different strategies
* Placeing items into container in certain order
  * Simplest solution is adding Items in any order to Container
  * More sophisticated are improvement heuristics or GRASP
