### ISSUE TITLE
your opinion about port it to PHP 8.2

### ISSUE THREAD

**Issue by br750** [hschneid/xflp#22]
Hello, 
Great job, thanks for sharing. it is likely that we will need to port it to PHP 8.2, do you think that the algo part will be complicated to re-write in PHP? Does this seem possible to you in this language, or do you think that certain difficulties will be difficult to solve?
thanks again

**Comment by hschneid** [comment]
Hi,

thanks for your question.

I'm not so good in PHP, but I used no special syntactic sugar in xflp. Hence I can't see, why a port to PHP wouldn't work.

It is just a mess of work to translate the Java code to PHP syntax. :-)

**Comment by br750** [comment]
Thanks for your answer
You are right, maybe a better solution would be to port your code to java API and communicate from PHP
Thanks again

**Comment by hschneid** [comment]
okay
