### ISSUE TITLE
NContainerOneTypeAddPacker#execute may cause OOM

### ISSUE THREAD

**Issue by Yiklam** [hschneid/xflp#24]
Hi.
If there is not any item can be add into container, the local variable 'containerList' may cause OOM.
![image](https://github.com/hschneid/xflp/assets/27883545/ec307649-ba05-46de-9e2a-add00c942d3d)
I think we should concern on the size of 'unpackedItem'. If it's size not change after 'createLoadingPlan', it should break the loop

![image](https://github.com/hschneid/xflp/assets/27883545/14f5e0e5-afa2-4a77-b40c-7d210d5024eb)

**Comment by hschneid** [comment]
Thanks for notice. :-) 

I solved this in branch #24... and merged it already into master.
