### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by ilya-kretov** [hschneid/xflp#30]
For some reason on my machine tests are not run unless I add this

test {
    useJUnitPlatform()
}

to the build.gradle

I've made a quick investigation and it seems that this is a quite common issue.
Am I missing something?

I tried on a clean project latests spock-core version available (2.4-M1-groovy-4.0) and it is not working w/o useJUnitPlatform instruction

**Comment by hschneid** [comment]
Hi,

the test for virtual items failed. You are right.

I merged the latest branch, where I removed the whole virtual item feature with this failing test.

Hence, it should work now with master.

**Comment by hschneid** [comment]
closed
